debug = false

logLevel = "ERROR"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "tinycloud.fr"
watch = true
exposedByDefault = false

[acme]
email = "christophe.cluizel@gmail.com"
storage = "acme.json"
caServer = "https://acme-staging-v02.api.letsencrypt.org/directory" # comment this line for production
entryPoint = "https"
onHostRule = true
[acme.httpChallenge]
entryPoint = "http"